image:https://img.shields.io/badge/stack%20overflow-jbossfuse-red.svg?colorB=cc0000[link="https://stackoverflow.com/questions/tagged/jbossfuse"]

= JBoss Fuse
:toc:
:icons: font

Red Hat JBoss Fuse is a lightweight, flexible integration platform that enables rapid integration
across the extended enterprise—on-premise or in the cloud.

Based on Apache Camel, Fuse leverages pattern-based integration, a rich connector catalog, and extensive
data transformation capabilities to enables users to integrate anything.

== Development Process

There are two ways of building JBoss Fuse 7:

* using Jenkins pipeline
* using plain old Maven

=== Building using Jenkins Pipeline

TO DESCRIBE

=== Building locally using Maven

Basic invocation of `mvn clean install` will build Fuse minimal and full distro. Minimal distribution is
maintained only for presentation and test purposes.

We can enable additional profiles:

* `mvn -Pcs validate` - Run checkstyle  checks
* `mvn -Plicense process-sources` - regenerate license headers in configured files using `license-header.txt`
* `mvn -Ptest verify` - run integration test inside `fuse-itests` module

(In order to generate license headers and/or perform checkstyle checks, it's recommended to use `-Plicense,test` and
`-Pcs,test` respectively).
