// Asciidoctor attributes

:toc: left
:sectnums:
:sectnumlevels: 3
:!linkcss:
:source-highlighter: highlightjs
:data-uri:

// custom attributes

:f7: Red Hat Fuse 7

= Fuse 7 persistence quickstarts

`quickstarts/persistence` examples show different aspects of persistence management in {f7}.

This complex topic is divided into several subprojects and examples.

== Persistence manual
`quickstarts/persistence/manual` Maven project is a collection of Asciidoc documents that can be processed into HTML documentation
containing in-depth information about JDBC, JMS, transactions, data source management, configuration etc.

This documentation can be built using:
[listing,options="nowrap"]
----
$ cd quickstarts/persistence/manual
$ mvn clean process-resources
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< org.jboss.fuse.quickstarts:manual >------------------
[INFO] Building Red Hat Fuse :: Quickstarts :: persistence :: manual 7.0.0.fuse-000171
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
...
[INFO] Rendered */quickstarts/persistence/manual/src/main/asciidoc/index.adoc
----

Final documentation can be found in `quickstarts/persistence/manual/target/generated-docs/index.html`.

== Database and configuration scripts

`quickstarts/persistence/databases` directory contains different scripts and examples which are not itself part of Maven artifact:

* `scripts` contains SQL scripts, referred to from chapter 1 of the manual (_Database configuration_)

* `cm` contains sample Configuration Admin factory configuration that may be used to configure JDBC connection pool
using `pax-jdbc` features

* `blueprints` contains sample Blueprint XML files that may be dropped directly to `$FUSE_HOME/deploy` directory
(after configuring docker-based databases) or used as reference examples for normal OSGi bundles

== Standalone example

`standalone-xa` Maven project contains JUnit tests showing some code-only examples:

* `StandaloneTxManagerTest` shows how to configure Narayana Transaction Manager and use it in canonical JTA example with XA recovery

* `StandaloneXADataAccessTest` shows how DBCP2 connections pools may be configured in Java™ code. This example's
goal is to clear confusion between database-specific and generic instances of `javax.sql.(XA)DataSource` interface implementations.

* `StandaloneWMQ9AccessTest` shows _canonical_ methods for accessing IBM MQ 9 broker. Because IBM MQ drivers are not accessible
via Maven Central repository, code examples use Spring configuration and there's special `wmq9` Maven profile
with `system`-scoped dependency. When running this example, we have to specify a property for the location
of MQ drivers.
+
[listing,options="nowrap"]
----
$ ls -la /data/downloads/ibm.com/IBM\ MQ/9.0.5.0-IBM-MQ-Install-Java-All/JavaSE/
total 12732
drwxrwxr-x. 2 ggrzybek ggrzybek    4096 04-13 16:20 .
drwxrwxr-x. 5 ggrzybek ggrzybek    4096 04-13 16:22 ..
-rw-rw-r--. 1 ggrzybek ggrzybek  775948 04-13 16:20 bcpkix-jdk15on-157.jar
-rw-rw-r--. 1 ggrzybek ggrzybek 3759724 04-13 16:20 bcprov-jdk15on-157.jar
-rw-rw-r--. 1 ggrzybek ggrzybek 8278943 04-13 16:20 com.ibm.mq.allclient.jar
-rw-rw-r--. 1 ggrzybek ggrzybek   43698 04-13 16:20 com.ibm.mq.traceControl.jar
-rw-rw-r--. 1 ggrzybek ggrzybek   22769 04-13 16:20 fscontext.jar
-rw-rw-r--. 1 ggrzybek ggrzybek   58349 04-13 16:20 jms.jar
-rw-rw-r--. 1 ggrzybek ggrzybek   77116 04-13 16:20 providerutil.jar

$ pwd
/home/ggrzybek/sources/github.com/jboss-fuse/fuse-karaf/quickstarts/persistence

$ mvn clean test -Pquickstarts-test -Pwmq9 -f standalone-xa/ -Dmq9library.path='/data/downloads/ibm.com/IBM MQ/9.0.5.0-IBM-MQ-Install-Java-All/JavaSE' -Dtest=StandaloneWMQ9AccessTest
[INFO] Scanning for projects...
[INFO]
[INFO] --------------< org.jboss.fuse.quickstarts:standalone-xa >--------------
[INFO] Building Red Hat Fuse :: Quickstarts :: persistence :: standalone transaction support 7.0.0.fuse-000171
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ standalone-xa ---
[INFO] Deleting /data/sources/github.com/jboss-fuse/fuse-karaf/quickstarts/persistence/standalone-xa/target
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ standalone-xa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /data/sources/github.com/jboss-fuse/fuse-karaf/quickstarts/persistence/standalone-xa/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ standalone-xa ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ standalone-xa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ standalone-xa ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /data/sources/github.com/jboss-fuse/fuse-karaf/quickstarts/persistence/standalone-xa/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ standalone-xa ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.jboss.fuse.quickstarts.persistence.standalone.StandaloneJMSAccessTest
14:07:54 INFO [StandaloneJMSAccessTest] (StandaloneJMSAccessTest.java:71) : MESSAGE: Hello IBM MQ 9
14:07:54 INFO [StandaloneJMSAccessTest] (StandaloneJMSAccessTest.java:72) : MESSAGE:
  JMSMessage class: jms_text
  JMSType:          null
  JMSDeliveryMode:  2
  JMSDeliveryDelay: 0
  JMSDeliveryTime:  0
  JMSExpiration:    0
  JMSPriority:      4
  JMSMessageID:     ID:414d512046555345514d2020202020207f89d45a05eff121
  JMSTimestamp:     1523880474298
  JMSCorrelationID: null
  JMSDestination:   queue:///DEV.QUEUE.1
  JMSReplyTo:       null
  JMSRedelivered:   false
    JMSXAppID: jar
    JMSXDeliveryCount: 1
    JMSXUserID: app
    JMS_IBM_Character_Set: UTF-8
    JMS_IBM_Encoding: 273
    JMS_IBM_Format: MQSTR
    JMS_IBM_MsgType: 8
    JMS_IBM_PutApplType: 28
    JMS_IBM_PutDate: 20180416
    JMS_IBM_PutTime: 12075430
Hello IBM MQ 9
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.717 s - in org.jboss.fuse.quickstarts.persistence.standalone.StandaloneJMSAccessTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.368 s
[INFO] Finished at: 2018-04-16T14:07:54+02:00
[INFO] ------------------------------------------------------------------------
----

* `StandaloneArtemisAccessTest` shows _canonical_ methods for accessing A-MQ 7 broker. This example should be run
with `-Partemis` Maven profile.

* `StandaloneAMQ6AccessTest` shows _canonical_ methods for accessing A-MQ 6 broker. This example should be run
with `-Pamq6` Maven profile.

== JavaEE example

`javaee-xa` is not OSGi related, but presents _canonical_ example of using JTA and JDBC APIs inside standard Servlet.
This example requires configuration of sample data sources inside Red Hat EAP server. The configuration details
are not presented in this quickstarts - only the API usage is shown.

== Camel JDBC example

`camel-jdbc` is a simple Camel context with routes that interact with camel-jdbc component. It is required
to configure docker-based PostgreSQL database (as presented in Persistence Manual).

Using fresh {f7} instance, we can (after building the example):
[listing,options="nowrap"]
----
karaf@root()> install -s mvn:org.postgresql/postgresql/42.2.2
Bundle ID: 233
karaf@root()> feature:install jdbc pax-jdbc-pool-dbcp2

karaf@root()> install -s mvn:org.jboss.fuse.quickstarts/camel-jdbc/7.0.0.fuse-000171
Bundle ID: 238
----

After installing the example, we'll see this log output every 20 seconds:

[listing,options="nowrap"]
----
2018-04-12 14:48:05,260 INFO  {Camel (camel) thread #8 - timer://webinar} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : *** Select all : {id=1, date=2018-02-20 08:00:00.0, name=User 1, summary=Incident 1, details=This is a report incident 001, email=user1@redhat.com}
2018-04-12 14:48:05,261 INFO  {Camel (camel) thread #8 - timer://webinar} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : *** Select all : {id=2, date=2018-02-20 08:10:00.0, name=User 2, summary=Incident 2, details=This is a report incident 002, email=user2@redhat.com}
2018-04-12 14:48:05,261 INFO  {Camel (camel) thread #8 - timer://webinar} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : *** Select all : {id=3, date=2018-02-20 08:20:00.0, name=User 3, summary=Incident 3, details=This is a report incident 003, email=user3@redhat.com}
2018-04-12 14:48:05,262 INFO  {Camel (camel) thread #8 - timer://webinar} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : *** Select all : {id=4, date=2018-02-20 08:30:00.0, name=User 4, summary=Incident 4, details=This is a report incident 004, email=user4@redhat.com}
----

Additionally, if a file will be created in `$FUSE_HOME/data/camel-jdbc`, additional query will be performed:
[listing,options="nowrap"]
----
$ echo -n '1,3' > data/camel-jdbc/query1.txt
----

After triggering `key-from-file` route using the above command, we'll see this in the log:
[listing,options="nowrap"]
----
2018-04-12 14:51:22,967 INFO  {Camel (camel) thread #7 - file://data/camel-jdbc} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : >>> SQL Query : select * from report.incident where id = '1'
2018-04-12 14:51:22,972 INFO  {Camel (camel) thread #7 - file://data/camel-jdbc} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : >>> Select using key : [{id=1, date=2018-02-20 08:00:00.0, name=User 1, summary=Incident 1, details=This is a report incident 001, email=user1@redhat.com}]
2018-04-12 14:51:22,973 INFO  {Camel (camel) thread #7 - file://data/camel-jdbc} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : >>> SQL Query : select * from report.incident where id = '3'
2018-04-12 14:51:22,977 INFO  {Camel (camel) thread #7 - file://data/camel-jdbc} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : >>> Select using key : [{id=3, date=2018-02-20 08:20:00.0, name=User 3, summary=Incident 3, details=This is a report incident 003, email=user3@redhat.com}]
----
