// Asciidoctor attributes

:toc: left
:sectnums:
:sectnumlevels: 3
:!linkcss:
:source-highlighter: highlightjs
:data-uri:

// custom attributes

:f7: Red Hat Fuse 7

= Fuse 7 persistence quickstarts

`quickstarts/persistence` examples show different aspects of persistence management in {f7}.

This complex topic is divided into several subprojects and examples.

== Persistence manual
`quickstarts/persistence/manual` Maven project is a collection of Asciidoc documents that can be processed into HTML documentation
containing in-depth information about JDBC, JMS, transactions, data source management, configuration etc.

This documentation can be built using:
[listing,options="nowrap"]
----
$ cd quickstarts/persistence/manual
$ mvn clean process-resources
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< org.jboss.fuse.quickstarts:manual >------------------
[INFO] Building Red Hat Fuse :: Quickstarts :: persistence :: manual 7.0.0.fuse-000171
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
...
[INFO] Rendered */quickstarts/persistence/manual/src/main/asciidoc/index.adoc
----

Final documentation can be found in `quickstarts/persistence/manual/target/generated-docs/index.html`.

== Database and configuration scripts

`quickstarts/persistence/databases` directory contains different scripts and examples which are not itself part of Maven artifact:

* `scripts` contains SQL scripts, referred to from chapter 1 of the manual (_Database configuration_)

* `cm` contains sample Configuration Admin factory configuration that may be used to configure JDBC connection pool
using `pax-jdbc` features

* `blueprints` contains sample Blueprint XML files that may be dropped directly to `$FUSE_HOME/deploy` directory
(after configuring docker-based databases) or used as reference examples for normal OSGi bundles

== Standalone example

`standalone-xa` Maven project contains JUnit tests showing some code-only examples:

* `StandaloneTxManagerTest` shows how to configure Narayana Transaction Manager and use it in canonical JTA example with XA recovery

* `StandaloneXADataAccessTest` shows how DBCP2 connections pools may be configured in Java™ code. This example's
goal is to clear confusion between database-specific and generic instances of `javax.sql.(XA)DataSource` interface implementations.

== JavaEE example

`javaee-xa` is not OSGi related, but presents _canonical_ example of using JTA and JDBC APIs inside standard Servlet.
This example requires configuration of sample data sources inside Red Hat EAP server. The configuration details
are not presented in this quickstarts - only the API usage is shown.

== Camel JDBC example

`camel-jdbc` is a simple Camel context with routes that interact with camel-jdbc component. It is required
to configure docker-based PostgreSQL database (as presented in Persistence Manual).

Using fresh {f7} instance, we can (after building the example):
[listing,options="nowrap"]
----
karaf@root()> install -s mvn:org.postgresql/postgresql/42.2.2
Bundle ID: 233
karaf@root()> feature:install jdbc pax-jdbc-pool-dbcp2

karaf@root()> install -s mvn:org.jboss.fuse.quickstarts/camel-jdbc/7.0.0.fuse-000171
Bundle ID: 238
----

After installing the example, we'll see this log output every 20 seconds:

[listing,options="nowrap"]
----
2018-04-12 14:48:05,260 INFO  {Camel (camel) thread #8 - timer://webinar} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : *** Select all : {id=1, date=2018-02-20 08:00:00.0, name=User 1, summary=Incident 1, details=This is a report incident 001, email=user1@redhat.com}
2018-04-12 14:48:05,261 INFO  {Camel (camel) thread #8 - timer://webinar} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : *** Select all : {id=2, date=2018-02-20 08:10:00.0, name=User 2, summary=Incident 2, details=This is a report incident 002, email=user2@redhat.com}
2018-04-12 14:48:05,261 INFO  {Camel (camel) thread #8 - timer://webinar} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : *** Select all : {id=3, date=2018-02-20 08:20:00.0, name=User 3, summary=Incident 3, details=This is a report incident 003, email=user3@redhat.com}
2018-04-12 14:48:05,262 INFO  {Camel (camel) thread #8 - timer://webinar} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : *** Select all : {id=4, date=2018-02-20 08:30:00.0, name=User 4, summary=Incident 4, details=This is a report incident 004, email=user4@redhat.com}
----

Additionally, if a file will be created in `$FUSE_HOME/data/camel-jdbc`, additional query will be performed:
[listing,options="nowrap"]
----
$ echo -n '1,3' > data/camel-jdbc/query1.txt
----

After triggering `key-from-file` route using the above command, we'll see this in the log:
[listing,options="nowrap"]
----
2018-04-12 14:51:22,967 INFO  {Camel (camel) thread #7 - file://data/camel-jdbc} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : >>> SQL Query : select * from report.incident where id = '1'
2018-04-12 14:51:22,972 INFO  {Camel (camel) thread #7 - file://data/camel-jdbc} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : >>> Select using key : [{id=1, date=2018-02-20 08:00:00.0, name=User 1, summary=Incident 1, details=This is a report incident 001, email=user1@redhat.com}]
2018-04-12 14:51:22,973 INFO  {Camel (camel) thread #7 - file://data/camel-jdbc} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : >>> SQL Query : select * from report.incident where id = '3'
2018-04-12 14:51:22,977 INFO  {Camel (camel) thread #7 - file://data/camel-jdbc} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : >>> Select using key : [{id=3, date=2018-02-20 08:20:00.0, name=User 3, summary=Incident 3, details=This is a report incident 003, email=user3@redhat.com}]
----
